version: "3.9"

services:
  db:
    image: postgres:15
    container_name: audiotranscrib_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-audiotranscrib}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-audiotranscrib_pass}
      POSTGRES_DB: ${POSTGRES_DB:-audiotranscrib_db}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
